web:
  image: trambam
  ports:
   - "3000:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/trambam
   - ROOT_URL=http://trambam.chatz.li
  restart: always
mongo:
  image: mongo:latest
  restart: always
